site_name: OpenCreator
site_description: Creator 5 full-custom-firmware project documentation
repo_url: https://github.com/FlashForge-C5-Modding-Group/OpenCreator
repo_name: FlashForge-C5-Modding-Group/OpenCreator
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - navigation.sections
    - content.action.edit
    - search.suggest
    - content.tooltips
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
 
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - abbr
  - pymdownx.snippets

plugins:
  - search

nav:
  - Home: index.md
  - Getting started: getting-started.md
  - Installation: installation-and-safety.md  
  - OpenCreator Legacy: opencreator-legacy.md
  - OpenCreator CFW: opencreator-cfw.md
  - OpenCreator CFW Features:  
  - OpenCreator for SBC: rpi-klipper.md    
  - Architecture: architecture.md
  - Print workflow: print-workflow.md
  - Printer Features: printer-features.md
  - Status and roadmap: status-and-roadmap.md
  - Project layout: project-layout.md
  - Contributing: contributing.md
  - Slicer Configuration: slicer-config.md
